<Project>
  <PropertyGroup>
    <DarpResultsAnalyzeTestProjects Condition="'$(DarpResultsAnalyzeTestProjects)' == ''"
      >false</DarpResultsAnalyzeTestProjects>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsTestProject)' == 'true' and '$(DarpResultsAnalyzeTestProjects)' != 'true'">
    <NoWarn>$(NoWarn);DR0004;DR0005</NoWarn>
  </PropertyGroup>

  <Target
    Name="DarpResultsAddReferenceDocumentationFiles"
    BeforeTargets="CoreCompile"
    DependsOnTargets="ResolveReferences"
  >
    <ItemGroup>
      <_DarpResultsReferenceDocumentation
        Include="@(ReferencePath->'%(RootDir)%(Directory)%(Filename).xml')"
        Condition="Exists('%(ReferencePath.RootDir)%(ReferencePath.Directory)%(ReferencePath.Filename).xml')"
      />
      <AdditionalFiles Include="@(_DarpResultsReferenceDocumentation)" />
    </ItemGroup>
  </Target>
</Project>
